[package]
name = "yasai-wasm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { version = "0.2" }
getrandom = { version = "0.2", features = ["js"] }
yasai = { git = "https://github.com/sugyan/yasai", tag = "0.5.0" }
